### ISSUE TITLE
Not all functions are listed in node options

### ISSUE THREAD

**Issue by hannuterasloihde** [zinen/node-red-contrib-nibeuplink#4]
I can only see the three functions as in the image.

<img width="508" alt="image" src="https://github.com/zinen/node-red-contrib-nibeuplink/assets/102947525/189eed07-1ef7-4648-b28a-afea1cf59028">

How can I access the rest of them that are listed in the readme?

**Comment by hannuterasloihde** [comment]
I was a bit hasty and read the readme incorrectly. Only the ones with the YES mentioned are implemented.
Would it be possible to implement the following (or why not all of them):

GET api/v1/systems/{systemId}/parameters | READSYSTEM
PUT api/v1/systems/{systemId}/parameters | WRITESYSTEM

**Comment by zinen** [comment]
Each line of code must be tested and confirmed. I wont do that if no one uses it.
Try installing this development branch. I can't test PUT request my self properly but you might be able.
`npm install https://github.com/zinen/node-red-contrib-nibeuplink.git#dev`
I rely on your feedback if this is working or not for the parameters GET and PUT request.

**Comment by hannuterasloihde** [comment]
I had a quick try.

The getParameters returns me an empty list, I don't know whether this should be returning me something.
<img width="301" alt="image" src="https://github.com/zinen/node-red-contrib-nibeuplink/assets/102947525/ae20eca1-3f89-44d3-81e0-ad718ccadbde">


The setParameters gives me an error.  I sent the following json as payload:
msg.payload=
{
    "settings": {
        "hot_water_boost": "1"
    }
}


<img width="1523" alt="image" src="https://github.com/zinen/node-red-contrib-nibeuplink/assets/102947525/24c1a84c-ede0-44dd-a986-b505eec6d0f3">

**Comment by zinen** [comment]
I found an error in the PUT one. You must give it a msg.payload to get anything back. I also found some errors with the GET one. I updated the code. Please install again with the link above. Should be version 0.3.1d now.

As pr the API:
[GET](https://api.nibeuplink.com/docs/v1/Api/GET-api-v1-systems-systemId-parameters_parameterIds[0]_parameterIds[1]) request input msg.payload must be an object with an array like `{"parameterIds":["hot_water_boost"]}`
[PUT](https://api.nibeuplink.com/docs/v1/Api/PUT-api-v1-systems-systemId-parameters) request input msg.payload must be an object with an object  like `{"settings":{"hot_water_boost": "1"}}`

**Comment by hannuterasloihde** [comment]
Both are now working. Thank you very much.

Looking at the other available functions, I don't have much use for them.

**Comment by hannuterasloihde** [comment]
Just noticed that there are two different status functions. Only one of them is currently implemented. Could you also add the function to get the overall status of them system:
GET api/v1/systems/{systemId}/status/system

**Comment by zinen** [comment]
Found out that I needed some other API call so I added all of them in there. Please install and test again. If all is good for you then I'll bump this package to version 1.0.0 as it seems finished now to me.

**Comment by hannuterasloihde** [comment]
I now tested all available functions and they work.

**Comment by zinen** [comment]
Perfect. Released new version 1.0.0 now.
