### ISSUE TITLE
New myuplink api for Nibe heatpumps

### ISSUE THREAD

**Issue by mkvarnst** [zinen/node-red-contrib-nibeuplink#6]
Thanks for putting in the effort om making a node for the Nibe api.
Nibe seems to be moving over from "nibeuplink" to "myuplink".
Luckily the the endpoints seems quite similar to i thought I might trick the node in to working with the new api but unfortunately I got stuck.

- I created an application in `dev.myuplink.com` (**not** `api.nibeuplink.com`)
- Filled in the client identifier and secret in the node and clicks update. 
- The node accesses `https://api.nibeuplink.com/oauth/authorize?response_type=code&client_id=....` 
- I manually change the url to `https://api.myuplink.com/oauth/authorize?response_type=code&client_id=....` 
- The response url gives me a "Your nibe-fetcher code"
- I paste the code into the _One time use authCode_ field and press update followed by done and deploy.
- The node returns the following error message to my debug node: `nibe config error: authCode seems too short. Try a new authCode. `

Hope you can steer me in the right direction.

**Comment by zinen** [comment]
I already started this work up here. https://github.com/zinen/node-nibe-fetcher-promise/tree/myuplink2024

But as I have no units online for me to test I got stuck. Currently my plan is to wait for when my system at home can be updated before I'm able to solve this and test it out.

**Comment by mkvarnst** [comment]
Nice one. Sorry for not noticing that repo.

**Comment by qabi** [comment]
> If you are willing to lend out your system. I could get started on testing - but else we just wait until my system is ready for myuplink.

I just got my system set up. I would be happy to help move the new "myuplink" integration along. I have the app created and ready. You are welcome to contact me directly at dth (at) geysirit (dot) dk.

**Comment by zinen** [comment]
A first beta release is now [avalible here](https://github.com/zinen/node-red-contrib-nibeuplink/tree/myuplink2024) and it can be installed like so. 
```
npm install https://github.com/zinen/node-red-contrib-nibeuplink/tree/myuplink2024
```
*Its very limited for now but you should be able to read some parameters fom the API now into node-red*
